/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.bean.userConfig
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.context.ApplicationContext
import org.springframework.context.support.ClassPathXmlApplicationContext

// we have to mention that this is spring boot project
@SpringBootApplication

class App {
    static void main(String[] args) {
        SpringApplication.run(App.class,args)
        ApplicationContext context = new ClassPathXmlApplicationContext("applicationContext.xml");

        // 2. Get the bean
        userConfig user = (userConfig) context.getBean("userConfig");

    }
}
