/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.classes.Man;
import org.example.classes.person;
import org.example.classes.personInvocationHandler;

import java.lang.reflect.Proxy;

public class App {


    public static void main(String[] args) {
        Man mohan = new Man("mohan " , 30, "delhi",  "india");
        ClassLoader mohanClassLoder= mohan.getClass().getClassLoader();
        Class[] interfaces =mohan.getClass().getInterfaces();
        person proxyMohan = (person) Proxy.newProxyInstance(mohanClassLoder, interfaces,new personInvocationHandler(mohan));
        proxyMohan.introduce(mohan.getName());



    }
}
